Refactoring before final submission
WiMoVE-OSS/docs pull request #3
Opened 2023-07-17 12:53 UTC by dasGoogle

This PR touches some details of the configuration, updates aspects where there have been changes in the code that make the documentation obsolete. 

It also attempts to unify the language used in the documentation.

2023-07-17 13:01 UTC, rgwohlbold requested changes
Some small issues

2023-07-17 13:01 UTC, rgwohlbold commented on docs/setup/ansible_setup.md
> +WiMoVE provides a package you can install on your OpenWrt router (WiMoVEd) but needs some additional services in your network to be useful:
We should use `wimoved` here

2023-07-17 13:01 UTC, rgwohlbold commented on docs/setup/ansible_setup.md
> +For this reason, we do not provide complete configuration files APs but rather guide you how to create them yourself.
There seems to be one `APs` to much here

2023-07-17 13:01 UTC, rgwohlbold commented on docs/setup/ansible_setup.md
> +1. Go to the web interface of one of your APs running OpenWRT and configure a WPA2-PSK wireless network for each radio you wish to use. You can set any SSID and password, you will overwrite them in a
We should use the spelling `OpenWrt`

2023-07-17 13:01 UTC, rgwohlbold commented on docs/setup/manual/access_point.md
> +This part of the guide will show you how to set up WiMoVEd on your OpenWrt Access Point.
We should consistently use the spelling `wimoved`

2023-07-17 13:01 UTC, rgwohlbold commented on docs/setup/manual/index.md
> +    Since we often modify our software, some details about the setup instructions might be out-of-date. In case you run into problems, feel free to take a look at the [Ansible deployment scripts](htt
I would leave out the "might be out of date". It sounds unprofessional if the documentation warns the reader about being out-of-date

2023-07-17 13:01 UTC, rgwohlbold commented on docs/setup/manual/parameters.md
> +The functionality of the route reflector can also be included in the gateway. This is however currently only described in the Snsible deployment guide. You will need to combine the FRR configuration
Ansible :)

2023-07-17 13:01 UTC, rgwohlbold commented on docs/setup/manual/route_reflector.md
> +# Setting Up a route reflector
We should use consistent casing in all documentation titles. I would prefer Title Case, but that needs to be used everywhere

2023-07-17 13:14 UTC, dasGoogle commented on docs/setup/manual/index.md
> +    Since we often modify our software, some details about the setup instructions might be out-of-date. In case you run into problems, feel free to take a look at the [Ansible deployment scripts](htt
See if the new version fits better

2023-07-17 13:44 UTC, rgwohlbold approved these changes
:shipit:

2023-07-18 07:52 UTC, Sohn123 approved these changes
Nice!

2023-07-18 07:52 UTC, merged